#ifndef ASSIGNMENT2_DATA_STRUCTURE_QUEUEFUNCTIONS_H
#define ASSIGNMENT2_DATA_STRUCTURE_QUEUEFUNCTIONS_H

#include <bits/stdc++.h>
#include "Queue.h"
using namespace std;



#endif //ASSIGNMENT2_DATA_STRUCTURE_QUEUEFUNCTIONS_H
